name: Go

on:
  push:
    tags: 
      - v*
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: |
        go mod download
        go mod verify

    - name: Ensure dist directory
      run: mkdir dist
      
    - name: Build Linux AMD64
      run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v -ldflags="-s -w" -o dist/infracheck_linux_amd64 ./cmd

    - name: Test
      run: go test -v ./...

    - name: Install hub
      run: |
        sudo apt-get -y install hub

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.PTA_TOKEN }}
      run: |
        TAG=${{ github.ref }}
        hub release create -a ./dist/infracheck_linux_amd64 -m "Release $TAG" $TAG
        
