name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: |
        go mod download
        go mod verify

    - name: Ensure dist directory
      run: mkdir dist
      
    - name: Build Linux AMD64
      run: GOOS=linux GOARCH=amd64 go build -v -o dist/infracheck_linux_amd64 ./...

    - name: Test
      run: go test -v ./...

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Install hub
      run: |
        sudo apt-get -y install hub

    - name: Create Release
      run: |
        TAG=$(git describe --abbrev=0 --tags)
        hub release create -a ./dist/infracheck_linux_amd64 -m "Release $TAG" $TAG
